name: Hangar Lojistik CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: 📥 Kodu Çek (Checkout)
      uses: actions/checkout@v4

    - name: 🐳 Docker Compose ile Projeyi Derle
      run: |
        docker compose build
